image:
  file: .gitpod.dockerfile
ports:
- port: 3000
- port: 6080
  onOpen: ignore
- port: 5900
  onOpen: ignore
tasks:
- init: yarn && yarn run rebuild:electron
  command: >
    jwm &
    yarn --cwd examples/electron start ../..
- command: sleep 20 && gp open demo.md
github:
  prebuilds:
    pullRequestsFromForks: true
